name: Manual Power Automate Trigger

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title for Power Automate / Teams card'
        required: true
        default: 'Manual Workflow Triggered'
      message:
        description: 'Message text for Power Automate / Teams card'
        required: true
        default: 'This workflow was manually triggered.'

jobs:
  send-to-power-automate:
    runs-on: ubuntu-latest

    steps:
      - name: Send Adaptive Card payload to Power Automate
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{
              \"type\": \"message\",
              \"attachments\": [
                {
                  \"contentType\": \"application/vnd.microsoft.card.adaptive\",
                  \"content\": {
                    \"$schema\": \"http://adaptivecards.io/schemas/adaptive-card.json\",
                    \"type\": \"AdaptiveCard\",
                    \"version\": \"1.4\",
                    \"body\": [
                      {
                        \"type\": \"TextBlock\",
                        \"size\": \"Large\",
                        \"weight\": \"Bolder\",
                        \"text\": \"${{ github.event.inputs.title }}\"
                      },
                      {
                        \"type\": \"TextBlock\",
                        \"text\": \"${{ github.event.inputs.message }}\n\nRepository: ${{ github.repository }}\nTriggered by: ${{ github.actor }}\",
                        \"wrap\": true
                      }
                    ]
                  }
                }
              ]
            }"
        env:
          WEBHOOK_URL: ${{ secrets.POWER_AUTOMATE_WEBHOOK_URL }}
